---
title: "R Notebook"
output: html_notebook
---


### Scores for Likert scale for app content sensitivity
```{r}
require(dplyr)
require(ggplot2)
library(gridExtra)  
library(reshape2)
library(data.table)
```

```{r}
# df2_ is the updated dataframe 
df <- df2[  , 131:158]
df <- df[, 1:16]
df$Negative_experiences <- df2_copy$Q164 
```

#### Check open ended questions
```{r}
df %>% select(Q6.3, Q6.5, )
```
```{r}
sprintf("fam= %s, colleague= %s", df[142 ,"Q6.3"],df[142 , "Q6.5"] )
```


```{r}
df <- df[!is.na(df) , ]

df <- df[!is.na(df$Q169_1) & !is.na(df$Q170_1), ]
df <- df[(df$Q169_1!= "N/A" & dfz$Q170_1!= "N/A"  ), ]
df <- df[(df$Q169_1!= "NA" & dfz$Q170_1 != "NA"), ]
```


### s for Im ide by side plots
```{r}
# image3 <- ggplot(dfz, aes(x = dfz$variable, na.rm = TRUE)) + geom_bar( fill = "cornflowerblue",color="black") +  labs(x = "Likert Scale for concern",  y = "Participants count", title = "Family member reads") + theme(axis.text.x = element_text(face = "bold", color = "#993333", size = 8, angle = 90))
# 
# image3c <- ggplot(dfz, aes(x = Q170_1, na.rm = TRUE)) + geom_bar(fill = "cornflowerblue",color="black") +  labs(x = "Likert Scale for concern",  y = "Participants count", title = "Colleague reads") + theme(axis.text.x = element_text(face = "bold", color = "#993333", size = 8, angle = 90))
# 
# grid.arrange(image4, image4c, ncol= 2)
```



```{r}
# df %>% filter_at(vars(1:7), any_vars(!is.na(.)))
df <- df[, -8]
df <- df[, -16]
df <- df[, -15]
# unique(df)
df[, 1:14][is.na(df[, 1:14])] <- "N/A"

df <- df[ df$Q169_1!= "N/A" , ]
df <- df[ df$Q169_2!= "N/A" , ]
df <- df[ df$Q169_7!= "N/A" , ]
df <- df[ df$Q170_3!= "N/A" , ]
df <- df[ df$Q170_7!= "N/A" , ]
df <- df[ df$Q170_5!= "N/A" , ]
```

```{r}
df$Q169_1 <- factor(df$Q169_1, levels = c("Completely unconcerned", "Somwhat unconcerned", "Neither concerned nor unconcerned", "Somwhat concerned", "Extremely concerned"), ordered = TRUE)
df$Q169_2 <- factor(df$Q169_2, levels = c("Completely unconcerned", "Somwhat unconcerned", "Neither concerned nor unconcerned", "Somwhat concerned", "Extremely concerned"), ordered = TRUE)
df$Q169_3 <- factor(df$Q169_3, levels = c("Completely unconcerned", "Somwhat unconcerned", "Neither concerned nor unconcerned", "Somwhat concerned", "Extremely concerned"), ordered = TRUE)
df$Q169_4 <- factor(df$Q169_4, levels = c("Completely unconcerned", "Somwhat unconcerned", "Neither concerned nor unconcerned", "Somwhat concerned", "Extremely concerned"), ordered = TRUE)
df$Q169_5 <- factor(df$Q169_5, levels = c("Completely unconcerned", "Somwhat unconcerned", "Neither concerned nor unconcerned", "Somwhat concerned", "Extremely concerned"), ordered = TRUE)
df$Q169_6 <- factor(df$Q169_6, levels = c("Completely unconcerned", "Somwhat unconcerned", "Neither concerned nor unconcerned", "Somwhat concerned", "Extremely concerned"), ordered = TRUE)
df$Q169_7 <- factor(df$Q169_7, levels = c("Completely unconcerned", "Somwhat unconcerned", "Neither concerned nor unconcerned", "Somwhat concerned", "Extremely concerned"), ordered = TRUE)
```
```{r}
df$Q170_1 <- factor(df$Q170_1, levels = c("Completely unconcerned", "Somwhat unconcerned", "Neither concerned nor unconcerned", "Somwhat concerned", "Extremely concerned"), ordered = TRUE)
df$Q170_2 <- factor(df$Q170_2, levels = c("Completely unconcerned", "Somwhat unconcerned", "Neither concerned nor unconcerned", "Somwhat concerned", "Extremely concerned"), ordered = TRUE)
df$Q170_3 <- factor(df$Q170_3, levels = c("Completely unconcerned", "Somwhat unconcerned", "Neither concerned nor unconcerned", "Somwhat concerned", "Extremely concerned"), ordered = TRUE)
df$Q170_4 <- factor(df$Q170_4, levels = c("Completely unconcerned", "Somwhat unconcerned", "Neither concerned nor unconcerned", "Somwhat concerned", "Extremely concerned"), ordered = TRUE)
df$Q170_5 <- factor(df$Q170_5, levels = c("Completely unconcerned", "Somwhat unconcerned", "Neither concerned nor unconcerned", "Somwhat concerned", "Extremely concerned"), ordered = TRUE)
df$Q170_6 <- factor(df$Q170_6, levels = c("Completely unconcerned", "Somwhat unconcerned", "Neither concerned nor unconcerned", "Somwhat concerned", "Extremely concerned"), ordered = TRUE)
df$Q170_7 <- factor(df$Q170_7, levels = c("Completely unconcerned", "Somwhat unconcerned", "Neither concerned nor unconcerned", "Somwhat concerned", "Extremely concerned"), ordered = TRUE)
```


```{r}
df <- df%>% mutate_if(is.factor, as.numeric)
summary(df)
```




