---
title: "Device sharing Behaviour"
output:
  html_document:
    df_print: paged
---
- Updated 
```{r}
library(dplyr)
library(ggplot2)
library(data.table)
library(tidyr)
library(reshape2)
```

### How frequently can someone else view the contents of notifications on your phone in any of the following places?
```{r}
# head(copy)
df <- copy[, 52:59]
head(df)
```

```{r}
# str(df)
summary(df)
sapply(df, class)
```

```{r}
df[, 1:8][is.na(df[, 1:8])] <- "Not reported"
# df <- df[ df$Q2.9_1!= "N/A" , ]
# df <- df[ df$Q2.9_2!= "N/A" , ]
# df <- df[ df$Q2.9_3!= "N/A" , ]
# df <- df[ df$Q2.9_4!= "N/A" , ]
# df <- df[ df$Q2.9_5!= "N/A" , ]
# df <- df[ df$Q2.9_6!= "N/A" , ]
# df <- df[ df$Q2.9_7!= "N/A" , ]
# df <- df[ df$Q2.9_8!= "N/A" , ]


df[] <- lapply(df, factor, levels = c("Never", "Few times a month", "Few times a week", "Once a day", "Few times a day", "Not reported")) 
nrow(df)
```

```{r}

c <- as.data.frame( sapply(X = df, FUN = table))
print(row.names(c))

c<- tibble::rownames_to_column(c, "Scale")

setnames(c, old = c("Q2.9_1",  "Q2.9_2", "Q2.9_3","Q2.9_4", "Q2.9_5", "Q2.9_6", "Q2.9_7", "Q2.9_8"), new = c('Home', 'Meetings', "Classes", "Seminars and presentations", "Cafeterias and restaurants", "Social gatherings", "Stores and markets", "Public transport" ))

colnames(c)

c$Scale <- factor(c$Scale, levels = c("Never", "Few times a month", "Few times a week", "Once a day", "Few times a day", "Not reported"), ordered = TRUE)
```

#### calculate the count N
```{r}
for (i in 2: 9){
  print(c[4, i] + c[5, i ])
}

```


```{r}

for (i in 2:9) {
  t <- sum(c[,i])
  # print(t)
  c[, i] <- 100 *( c[, i]/t)
  c[, i] <- round(c[, i], 2)
}

# t <- sum(c$Q2.9_3)
# t
# c[, 1:8]<- 100 *( c[, 1:8]/t)
# c <- round(c, 2)
```


```{r}
for(i in 0:7){
  print(d[6*i +5, c("value")] + d[6*i +4, c("value")])
}
```


```{r}
d <- melt(c, id.vars="Scale")

# Everything on the same plot
# ggplot(d, aes(Scale,value, col=variable)) + geom_point() + stat_smooth() 

img <- ggplot(d,  aes(Scale,value, col=variable)) +
  geom_bar(stat='identity', position='dodge') +  
  labs( x= "Scale",  y = "Percentage of Participants") + 
  theme(legend.position =  c(.95, .95),legend.justification = c("right", "top"), legend.text = element_text(size = 20), axis.text.x = element_text(face = "bold", size = 20, angle = 15), axis.title.y = element_text(size = 20, angle = 90), axis.text=element_text(size=15),
        axis.title=element_text(size=14,face="bold")) + 
  geom_text(aes(label = value),position = position_dodge(1.0), vjust = -0.5, size= 5.5)
   
plot(img)

png("device.png", 1050, 900)

plot(img)
dev.off()

# Separate plots
# ggplot(d, aes(Scale,value)) + 
#   geom_point() + 
#   stat_smooth() +
#   facet_wrap(~variable)
```

#### Check values in 'others' text of previous question
```{r}
df <- copy[, 60:61]
(df)

df[, 1:2][is.na(df[, 1:2])] <- "N/A"
df <- df[ df$Q2.9_9_TEXT!= "N/A" , ]
df <- df[ df$Q2.9_9_TEXT!= "na" , ]
df <- df[ df$Q2.9_9_TEXT!= "n/a" , ]
df <- df[ df$Q2.9_9_TEXT!= "none" , ]
df <- df[ df$Q2.9_9_TEXT!= "None" , ]
df <- df[ df$Q2.9_9_TEXT!= "Nothing" , ]
df <- df[ df$Q2.9_9_TEXT!= "nothing" , ]
df <- df[ df$Q2.9_9_TEXT!= "Nobody" , ]

df[order( df[,1] ),]

dp <-as.data.frame( table(df$Q2.9_9))
dp
```



### How freq do you share your phone? 
```{r}
df <- copy[62: 68]
head(df)
```

```{r}
# df<- df %>% drop_na()
df[, 1:7][is.na(df[, 1:7])] <- "Not reported"
df[] <- lapply(df, factor, levels = c("Never", "Less than once a week", "Few times a week", "Multiple times a week", "Once a day", "Few times a day", "Multiple times a day", "N/A", "Not reported")) 

nrow(df)
summary(df)
```

```{r}
c <- as.data.frame( sapply(X = df, FUN = table))
c<- tibble::rownames_to_column(c, "Scale")

# c <- c[ c$Scale != "N/A", ]  #remove N/As
```

#### calculate value of N
```{r}
for(i in 2:8){
  print(c[5, i] + c[6, i] + c[ 7,i])
}
```

```{r}
#convert to percentage
for (i in 2:8) {
  t <- sum(c[,i])
  # print(t)
  c[, i] <- 100 *( c[, i]/t)
  c[, i] <- round(c[, i], 2)
}

c$Scale <- factor(c$Scale, levels = c("Never", "Less than once a week", "Few times a week", "Multiple times a week", "Once a day", "Few times a day", "Multiple times a day", "N/A", "Not reported"), ordered = TRUE)
setnames(c, old = c("Q3.4_1","Q3.4_2", "Q3.4_3", "Q3.4_4", "Q3.4_5", "Q3.4_6", "Q3.4_7"), new = c('Spouse', 'Siblings', "Parents", "Children older than 13", "Friends", "Colleagues", "Strangers"))

d <- melt(c, id.vars="Scale")

# Everything on the same plot
# ggplot(d, aes(Scale,value, col=variable)) + geom_point() + stat_smooth() 
```

#### calculate percentage for at least once a day
```{r}
for(i in 0:6){
  print(d[9*i +5, c("value")] + d[9*i +6, c("value")] + d[9*i + 7, c("value")])
}
```


#### Plot
```{r}
img <- ggplot(d,  aes(Scale,value, col=variable)) +
  geom_bar(stat='identity', position = "dodge") +  
  labs( x= "Scale",  y = "Percentage of Participants") + 
  theme(legend.position =  c(.95, .95),legend.justification = c("right", "top"), legend.text = element_text(size = 20), axis.text.x = element_text(face = "bold", size = 20, angle = 25), axis.title.y = element_text(size = 20, angle = 90), axis.text=element_text(size=15),
        axis.title=element_text(size=14,face="bold")) + 
  geom_text(aes(label = value),position = position_dodge(1.0), vjust = -0.5, size= 5.5)

plot(img)
png("device2.png", 1080, 900)
plot(img)
dev.off()
```

```{r}
rm(i)
rm(a1)
library(tidyselect)
rm(list = ls(pattern = "^cpearson"))
```
