---
title: "5.Technical Efficacy"
---
```{r}
df <- df2[ , c("Q10.1_1", "Q10.1_2" , "Q10.1_3", "Q10.1_4", "Q10.1_5", "Q164" )]

df[, 1:6][is.na(df[, 1:6])] <- "N/A"
df <- df[ df$Q10.1_1!= "N/A" , ]
df <- df[ df$Q10.1_2!= "N/A" , ]
df <- df[ df$Q10.1_3!= "N/A" , ]
df <- df[ df$Q10.1_4!= "N/A" , ]
df <- df[ df$Q10.1_5!= "N/A" , ]

df$Q164 <- as.character(df$Q164)
df <- df[(df$Q164 )!= "N/A", ]
df <- df[! is.na(df$Q164 ), ]
unique(df$Q164)

```


#### Convert to Factors
```{r}
df$Q10.1_1 <- factor(df$Q10.1_1, levels = c("Disagree", "Rather disagree", "Neither disagree, neither agree", "Rather agree", "Agree"), ordered = TRUE)
df$Q10.1_2 <- factor(df$Q10.1_2, levels = c("Disagree", "Rather disagree", "Neither disagree, neither agree", "Rather agree", "Agree"), ordered = TRUE)
df$Q10.1_3 <- factor(df$Q10.1_3, levels = c("Disagree", "Rather disagree", "Neither disagree, neither agree", "Rather agree", "Agree"), ordered = TRUE)
df$Q10.1_4 <- factor(df$Q10.1_4, levels = c("Disagree", "Rather disagree", "Neither disagree, neither agree", "Rather agree", "Agree"), ordered = TRUE)
df$Q10.1_5 <- factor(df$Q10.1_5, levels = c("Disagree", "Rather disagree", "Neither disagree, neither agree", "Rather agree", "Agree"), ordered = TRUE)
df$Q164 <- factor(df$Q164, levels = c("0", "1-2", "3-5", "6-10", "11-20", "More than 20", ordered= TRUE  ))
```


```{r}
summary(df)
```

```{r}
require(dplyr)
df <- df %>% mutate_if(is.factor, as.numeric)
str(df)
```

```{r}
df <- df %>% mutate(TechEfficacyScore = rowSums(.[1:5]) )

b1 <- aov(Q164 ~ TechEfficacyScore, data = df)
summary(b1)
```

### Score comparison with Negative Experiences

```{r}
df_m <- df
df_m %>%  group_by(df_m$Q164) %>% summarise(Mean_TechEfficacyScore = round(mean(TechEfficacyScore, na.rm = TRUE),2),  median_TechEfficacyScore = median(TechEfficacyScore, na.rm = TRUE))
```


```{r}
library(data.table)
setnames(df_m, old = c("Q10.1_1","Q10.1_2", "Q10.1_3", "Q10.1_4", "Q10.1_5", "Q164"), new = c('Q1','Q2', 'Q3', 'Q4', "Q5", "Neg_Exp"))

source("http://www.sthda.com/upload/rquery_cormat.r")
rquery.cormat(df_m)

```



### Summary of score
```{r}
range(df_m$TechEfficacyScore)
sd(df_m$TechEfficacyScore)
mean(df_m$TechEfficacyScore)
median(df_m$TechEfficacyScore)
```


#### 
```{r}
print("SD:")
apply(df,2,sd, na.rm = TRUE)
print("Mean")
round(apply(df,2,sd,na.rm = TRUE), 2)
apply(df,2,median, na.rm = TRUE)

# OR
summary(df)
```







